# Generated by Django 3.0.5 on 2020-04-18 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200418_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
